/**
 * A part of a skin texture.
 */
export enum SkinPart {
	HEAD_OVERLAY_FACE = "HEAD_OVERLAY_FACE",
	HEAD_TOP = "HEAD_TOP",
	HEAD = "HEAD",
	FACE = "FACE",
	HEAD_LEFT = "HEAD_LEFT",
	HEAD_RIGHT = "HEAD_RIGHT",
	HEAD_BOTTOM = "HEAD_BOTTOM",
	HEAD_BACK = "HEAD_BACK",
	BODY_FRONT = "BODY_FRONT",
	BODY = "BODY",
	BODY_FLAT = "BODY_FLAT",
	LEFT_ARM_TOP = "LEFT_ARM_TOP",
	RIGHT_ARM_TOP = "RIGHT_ARM_TOP",
	LEFT_ARM_FRONT = "LEFT_ARM_FRONT",
	RIGHT_ARM_FRONT = "RIGHT_ARM_FRONT",
	LEFT_LEG_FRONT = "LEFT_LEG_FRONT",
	RIGHT_LEG_FRONT = "RIGHT_LEG_FRONT",
}
