name: Deploy Lib

on:
  push:
    branches: ["master"]
    paths: [".gitea/workflows/deploy-lib.yml", "Lib/**"]

jobs:
  docker:
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        git-version: ["2.44.0"]
    runs-on: ${{ matrix.arch }}
    defaults:
      run:
        working-directory: ./Lib

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Install Dependencies
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      # Run Tests
      - name: Run Tests
        run: bun test

      - name: debug
        run: echo ${{ secrets.PUBLISH_NPM_TOKEN }}

      # Publish to NPM
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
