name: Deploy Frontend

on:
  push:
    branches: ["master"]
    paths: [".gitea/workflows/deploy-frontend.yml", "Frontend/**"]

jobs:
  docker:
    strategy:
      matrix:
        java-version: ["17"]
        maven-version: ["3.8.5"]
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: "./Frontend"

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Deploy to Dokku
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@10.10.3.28:22/restfulmc-web"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
