name: Deploy Lib

on:
  push:
    branches: ["master"]
    paths: ["Lib/**"]

jobs:
  docker:
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        git-version: ["2.44.0"]
        node-version: ["20.x"]
    runs-on: ${{ matrix.arch }}
    defaults:
      run:
        working-directory: ./Lib

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Run Tests
      - name: Run Tests
        run: bun test

      # Publish to NPM
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
