name: Deploy Lib

on:
  push:
    branches: ["master"]
    paths: [".gitea/workflows/deploy-lib.yml", "Lib/**"]

jobs:
  docker:
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        git-version: ["2.44.0"]
    runs-on: ${{ matrix.arch }}
    defaults:
      run:
        working-directory: ./Lib

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      # Run Tests
      - name: Run Tests
        run: bun test

      # Publish to NPM
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
