name: Publish JS SDK

on:
  push:
    branches: ["master"]
    paths: [".gitea/workflows/deploy-lib.yml", "JS-SDK/**"]

jobs:
  docker:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: "./JS-SDK"

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Install Dependencies
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      # Run Tests
      - name: Run Tests
        run: bun test

      # Publish to NPM
      - name: Publish to NPM
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
